name: Coverage Deployment

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  TEST_BINARIES: "ai_unit_tests gui_unit_tests server_unit_tests"
  PROJECTS: "src/ai src/gui src/server"

jobs:
  coverage-deploy:
    if: github.repository == 'neo-jgrec/zappy'
    environment:
      name: coverage
      url: ${{ steps.deployment-coverage.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libcriterion-dev
          sudo apt-get install -y libsfml-dev
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y gcovr

      - name: Build the tests
        working-directory: ${{ github.workspace }}
        run: make tests_run

      - name: Run the tests
        working-directory: ${{ github.workspace }}
        run: |
          for binary in $TEST_BINARIES; do
            ./$binary
          done

      - name: Generate the coverage reports
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p coverage
          for project in $PROJECTS; do
            gcovr . -r $project --html --html-details -o coverage/${project##*/}.html --exclude $project/tests
          done

      - name: Create index.html
        working-directory: ${{ github.workspace }}
        run: |
          echo "<html><head><title>Coverage reports</title></head><body>" > coverage/index.html
          for project in $PROJECTS; do
            echo "<a href='${project##*/}.html'>${project##*/}</a><br>" >> coverage/index.html
          done
          echo "</body></html>" >> coverage/index.html

      - name: Deploy the coverage reports
        id: deployment-coverage
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./coverage
          cname: zappy.jeffroy.eu
          deploy_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
