name: Deploy static content to Pages

on:
  push:
    branches: ['docs']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  TEST_BINARIES: "ai_unit_tests gui_unit_tests server_unit_tests"
  PROJECTS: "src/ai src/gui src/server"

jobs:
  deploy:
    if: github.repository == 'neo-jgrec/zappy'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          sudo apt update
          sudo apt install -y libcriterion-dev
          sudo apt install -y libsfml-dev
          sudo apt install -y libboost-all-dev
          sudo apt install -y python3-pip
          pip3 install gcovr

      - name: Fetch all branches
        working-directory: ${{ github.workspace }}
        run: git fetch --all

      - name: Checkout `main` branch
        working-directory: ${{ github.workspace }}
        run: git checkout main

      - name: Build the tests
        working-directory: ${{ github.workspace }}
        run: make tests_run

      - name: Run the tests
        working-directory: ${{ github.workspace }}
        run: |
          for binary in $TEST_BINARIES; do
            ./$binary
          done

      - name: Generate coverage report
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p coverage
          for project in $PROJECTS; do
            gcovr . -r $project --html --html-details -o coverage/${project##*/}.html --exclude $project/tests --html-theme github.dark-blue
          done

      - name: Switch to `docs` branch with coverage report
        working-directory: ${{ github.workspace }}
        run: |
          git checkout docs
          mkdir -p static/coverage
          mv coverage/* static/coverage

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
